### PR TITLE
Fixed my wrong.

### PR DESCRIPTION
**Pull request by hardcoreMG**
Because of my IDE is Xcode and it have a built-in git,my files and my folders is incorrect.If you know what should I do,tell me please!

### CODE REVIEW

**Comment by YiqinZhao** [comment]
# Reject

For your question: Xcode built-in git. This thing should be a feature of Xcode. So I will suggest that don't create projects inside this git repo. You may create a project somewhere else.

Or, if you still want to use one repo, you can only commit the robot.cpp file.

😝 But your pull request is still rejected  because your demonstration is so poor. When you demonstrate some thing you can't say if it works, it works correctly. You should try another solution for this puzzle, such as mathematic approach.

💪💪💪
Go ahead!

**Comment by hardcoreMG** [comment]
I really really don't know how to finish the demonstrate.Can you give me some advice?My solution
is traverse all of case,so what can I write?Thank you.

**Comment by YiqinZhao** [comment]
Well, I think you could build a mathematic model with 3 variables. Then you will get some equations, by solving those equations you will get an answer set. Try to compare the answer you get from your program and the one from your mathematic model, things will be more clear.

**Comment by hardcoreMG** [comment]
These equations that I can't build.I have no ideas about it.If my code have no wrongs,I hope you could accept my pull request.I will think this puzzle more.Thanks!

**Comment by YiqinZhao** [comment]
Don't give up. Let me just give you some hints:

- **Split this puzzle into serval parts**
- Try to figure out the equations about the incoming time *T1* and the returning time *T2*
- Add constraint inequalities to the battery usage.
- Add constraint inequalities to the range of *T1*, *T2*.
- Calculate the total time *T* using program.
- Compare between answers from your code and the demonstration code.

In another word, building a purely mathematic model is difficult, but you can build multiple equitations and calculate them one by one.

In this way you are actually not demonstrated your answer, but verified it. However, it is good enough.

One more thing, just another idea come to my mind, maybe you can write some unit tests to ensure your code works correctly.

Be patient, boy, you are good enough. But you could definitely do better.

**Pull request closed without merging**
